<Project>
  <PropertyGroup>
    <Version>1.7.11</Version>
    <AssemblyVersion>1.7.11.0</AssemblyVersion>
    <FileVersion>1.7.11.0</FileVersion>
    <InformationalVersion>1.7.11</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
</Project>
