<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>..\..\assets\icons\AppIcon.ico</ApplicationIcon>
    <AssemblyName>ChromeIsolator</AssemblyName>
    <RootNamespace>ChromeIsolator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\assets\icons\AppIcon.ico" Link="Assets\AppIcon.ico" />
  </ItemGroup>
</Project>
